version: "2"
 
services:
  service:
    build: ./Service
    ports:
      - "5000:5000"
 
  webapp:
    build: ./webapp
    volumes:
      - .\WebApp:/WebApp
      - /WebApp/node_modules
    ports:
      - "5001:5000"

  #redis:
  #  image: redis:alpine
  #  ports: ["6379"]
 
  #worker:
  #  build: ./worker
 
  #db:
  #  image: postgres:9.4
 
  #result:
  #  build: ./result
  #  command: nodemon --debug server.js
  #  volumes:
  #    - ./result:/app
  #  ports:
  #    - "5001:80"
  #    - "5858:5858" 
